giftstrings = [ # Gift emoji will be prefixed to these strings.
  "{0} just sent a 🏈 Football to {1}. John Madden is proud of you.",
  "{0} just sent a 📹️ GIF to {1}. Its expiration date was supposed to be years ago.",
  "{0} just sent a 🪆 Matryoshka doll to {1}. There's a lot of dolls in one single package!",
  "{0} just sent a 🎮 Video Game to {1}. Unfortunately, a sequel has been released right now.",
  "{0} just sent a 🛷 Sled to {1}. It's completely useless without snow!",
  "{0} just sent a ⭐ Star to {1}. {1} absorbed the star somehow.",
  "{0} just sent a 🎱 Magic 8 Ball to {1}. It's good for everything except predictions.",
  "{0} just sent a 🏁 Checkered Flag to {1}. {1} wins a race thanks to it.",
  "{0} just sent a 🏳️ White Flag to {1}, surrendering themselves to {1}.",
  "{0} just sent a 🍪 Cookie to {1}. {1} promptly attempts to click on it.",
  "{0} just sent a <:googlecat:494963974442319872> Cat to {1}. The cat climbs up a furniture, ignoring everyone.",
  "{0} just sent a <:googledog:612123002938720257> Dog to {1}. The dog aims for the couch, thrashing it completely.",
  "{0} just sent a 🎀 Bow to {1}. A perfect accessory for a doll or a pet.",
  "{0} just sent a <:bloblamp:580597913600655370> Lamp to {1}. Wait a minute, there's not supposed to be a blob!",
  "{0} just sent a <:b4nzyblob:396521772905922562> b1nzy blob to {1}. The power of the ban hammer scares {1} away.",
  "{0} just sent a 🏎️ Toy Car to {1}. The toy car managed to give hours of entertainment successfully.",
  "{0} just sent a 🏆 Trophy to {1}. This is the way you celebrate your moment of victory, if you had one!",
  "{0} just sent a 🍰 Piece of Cake to {1}. Sadly, you've been lied to, it's not real.",
  "{0} just sent a 🔋 Battery to {1}. Toys are not included with the battery.",
  "{0} just sent a 🦠 Microbe to {1}. {0} and {1} have been quarantined immediately.",
  "{0} just sent a 📷 Camera to {1}. It's completely irrelevant nowadays.",
  "{0} just sent a 📱 Smartphone to {1}. Do you folks not have phones?!",
  "{0} just sent a 📕 Book to {1}. The perfect source of information, but a terrible one for rainbows.",
  "{0} just sent a ⚾ Baseball to {1}. {1} catches it successfully!",
  "{0} just sent a 💿 CD to {1}. You already downloaded its content before.",
  "{0} just sent a 📀 DVD to {1}. There's nothing that can read its contents!",
  "{0} just sent a 💻 Laptop to {1}. It's portable and powerful.",
  "{0} just sent 🇧🇷 Brazil to {1}. {1} is going there, and so are you.",
  "{0} just sent a 🪃 Boomerang to {1}. They're certainly gonna get it back, though.",
  "{0} just sent an 🥚 Egg to {1}. Can I offer you a nice egg in this trying time?",
  "{0} just sent a <:googlecrab:561738206345953311> Crab to {1}. If you bring it close to your ear, you can hear what it sounds like to be attacked by a crab.",
  "{0} just sent a 🖨️ Printer to {1}. It's cheaper than just buying new cartridges.",
  "{0} just sent a 🕵️ Spy to {1}. Please don't tell them until the investigation has concluded.",
  "{0} just sent ✂️ Scissors to {1}. They need another pair to open the wrapper though.",
  "{0} just sent a 🥁 Drum to {1}. I believe {0} hates {1}'s parents.",
  "{0} just sent a 💐 Bouquet to {1}. {1} blushes intensively.",
  "{0} just sent 🥫 Dog Food to {1}. It might actually be for their dog, but who knows.",
  "{0} just sent a 🛵 Scooter to {1}. By using it, {1} can change position.",
  "{0} just sent a 🗨️ Text Balloon to {1}. This isn't a comic at all!",
  "{0} just sent 💰 Money to {1}. Gifts are cool, but we all like cold hard cash too.",
  "{0} just sent a 🏹 Bow to {1}. {1} doesn't know archery and expected something for their doll or pet.",
  "{0} just sent a 🎃 Pumpkin to {1}. {0} still thinks that it's October.",
  "{0} just sent an 🦉 Owl to {1}. An awesome friend, especially during sleepless nights.",
  "{0} just sent a 🛑 Stop Sign to {1}. It has 8 fantastic sides and 8 awesome angles!",
  "{0} just sent 🧻 Toilet Paper to {1}. A very expensive gift, take care of it.",
  "{0} just sent 🧂 Salt to {1}. In case League of Legends doesn't bring enough.",
  "{0} just sent a <:googlerat:674555360312295424> Rat to {1}. It preys at night and stalks at night.",
  "{0} just sent a 🌭 Hot Dog to {1}. Still better than dog food I guess?",
  "{0} just sent a 🎸 Guitar to {1}. After doing a sick guitar solo, {1} smashes it on the ground.",
  "{0} just sent a 🤖 Bot to {1}. Let's hope it doesn't use JavaScript.",
  "{0} just sent 👀 Eyes to {1}. Having a second pair of eyes on your work is always useful!",
  "{0} just sent a <:googleduck:727972837167595521> Duck to {1}. It's not as good as rubber ducks.",
  "{0} just sent a 🦷 Tooth to {1}. You don't want to know where it comes from.",
  "{0} just sent a 🪨 Rock to {1}. {1} counterattacks with paper!",
  "{0} just sent a 🥖 Baguette to {1}. Ah oui, this is a very good cadeau.",
  "{0} just sent a 🐛 Bug to {1}. As if they didn't write enough bad code already.",
  "{0} just sent a 👑 Crown to {1}. Everyone bow to {1} **XIV the Great** now!",
  "{0} just sent a 🏴‍☠️ Pirate Flag to {1}. Both do be pirates now, but be arrested after leavin' the Bay.",
  "{0} just sent an 🧯 Extinguisher to {1}. If it ever catches fire itself, just put it away with the rest of the fire.",
  "{0} just sent a 🧓 Boomer to {1}. People say \"ok boomer\" but never ask \"Are you ok, boomer?\"",
  "{0} just sent an ⏰ Alarm Clock to {1}. The alarm rings, {1} was dreaming the whole time.",
  "{0} just sent a 💍 Ring to {1}. {0} and {1} are now engaged!",
  "{0} just sent a 🪵 Log to {1}. Does anyone even read this thing?",
  "{0} just sent 🥢 Chopsticks to {1}. {1} has no idea how to use them.",
  "{0} just sent a ♟ Pawn to {1}. Is this a challenge?",
  "{0} just sent an 🪓 Axe to {1}. {0} missed, thankfully.",
  "{0} just sent a 🪙 Coin to {1}. Due to past experiences, you dread the coin.",
  "{0} just sent a 🧩 Jigsaw Piece to {1}. The puzzle finally can be solved after all these years.",
  "{0} just sent a 🛹 Skateboard to {1}. It's a perfect time to be a cool kid.",
  "{0} just sent a 🔫 Water Gun to {1}. Who would give murder machines to an innocent person?!",
  "{0} just sent a 😂 Joy Emoji to {1}. It's so foul, that not even a blob equivalent would be better.",
  "{0} just sent a <:blob:530901399077388289> Blob to {1}. It has no feelings, no emotions, just blob.",
  "{0} just sent a 🌝 Moon to {1}. It crashes on Earth and {1} fails to stop it.",
  "{0} just sent <:stairs:779924876286623784> Stairs to {1}. {0} warned them about the stairs but {1} fell down on them. It keeps happening.",
  "{0} just sent a 📺 Television to {1}. It just keeps saying \"But wait, there's more!\".",
  "{0} just sent a 💾 Floppy Disk to {1}. Don't copy that floppy!",
  "{0} just sent a <:bolb:453933426555486208> Bolb to {1}. Bolb is silly, Bolb is lovely, Bolb is simply Bolb.",
  "{0} just sent a <:googlebee:612122990338899995> Bee. According to all laws of gift distribution, a bee shouldn't be a gift.",
  "{0} just sent a <:greentick:567088336166977536> Green Tick to {1}. <:greentick:567088336166977536> moved to <#289847856033169409>: {1} (by {0})",
  "{0} just sent a 🎁 Gift to {1}. Inside the gift that was inside another gift, there's nothing.",
  "{0} just sent a <:redtick:567088349484023818> Red Tick to {1}. {1} isn't being added as an emoji today.",
  "{0} just sent a 🔮 Crystal Ball to {1}. The future has been revealed to {1}."
  "{0} gave a 👾 Space Invader to {1}. {1} is doomed, DOOMED!"
  "{0} gave a ♟️️Pawn to {1}. Checkmate!"
  "{0} gave a 🥧️ Pie to {1}. I wonder if it can tell the time..."
  "{0} just sent a 🐉 Dragon to {1}. King Dragon sends his regards."
  "{0} just sent a 🪕 Banjo to {1}. Hey, where's Kazooie?"
  "{0} just sent a 🥏 Frisbee to {1}. TWO POINTS!"
  "{0} just sent a 🥮 Moon Cake to {1}. What a time to be alive."
  "{0} sent a 🚌 Bus to {1}. Hope that {1} likes to party!"
  "{0} sent a 🍕 Pizza to {1}.  Little-known fact: vampires are weak to it."
  "{0} sent a 🐺 Wolf to {1}.  One down, thirteen to go."
  "{0} sent a 🪣 Bucket to {1}.  There's more."
  "{0} sent a 🍙 Donut to {1}.  I hope it's jelly-filled!"
]
